fix: clean up kms chainId init and mutation constraints (#147)
Have the following 2 issues when signing:

```
64 |     const maxPointS = BigInt(
65 |       "0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141"
66 |     );
67 |     const halfPointS = maxPointS / 2n;
68 |     if (signature.s > halfPointS) {
69 |       signature.s = maxPointS - signature.s;
           ^
TypeError: Attempted to assign to readonly property.
```

and a parse issue which was caused by not awaiting a chainId response:

```
12 | function hash(data) {
13 |   return sha256(data);
14 | }
15 | __name(hash, "hash");
16 | function uint64ToBytesBE(value) {
17 |   const bigIntValue = BigInt(value);
                           ^
SyntaxError: Failed to parse String to BigInt
``

---------

Co-authored-by: Mike Christopher <mchristopher@users.noreply.github.com>