fix: expose mutations callbacks (#97)
Adds missing `@fuels/react` mutation callbacks and removing redundant
arrow functions from every `useMutation`.
It enables developers to access mutations options, such as `onError` and
`onSuccess`.

### Examples

```tsx
const { sendTransaction } = useSendTransaction();

// [...]

sendTransaction(
  {
    address: 'fuel1z...',
    transaction,
  },
  {
    onError: (error) => {
      // Here we can do anything we want, for example, display a toast
      console.log(error);
    },
  },
);
```